packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/create-flex-plugin.js, packages/create-flex-plugin/templates/src/DemoPlugin.js, packages/flex-plugin/package.json, packages/flex-plugin/src/flex-plugin.ts
This PR has a few things going on around typings:
1) This will pin the version that is being used in plugin projects to make sure it's always the same as the one that is actually being loaded in `index.html`
2) It adds JSDoc headers to the `init()` method in the plugin template to provide types and autocomplete even if the user is not using TypeScript
3) I restructured the types to fix the Type error in the load() function of the `flex-plugin` package
=> :sparkles: Fix typings and add jsDoc header 

packages/create-flex-plugin/templates/package.json, packages/flex-plugin/package.json
This inherits a pinning of React to 16.5.2 to address version mismatches moving forward in plugins leading to errors such as
=> Bump flex-ui to 1.1.1

packages/flex-plugin/bin/check-start, packages/flex-plugin/package.json, packages/react-app-rewire-flex-plugin/lib/index.js
Apparently symlinking is tough on Windows as it requires Admin privileges. 
So instead I'm copying the file (and override it if necessary) into the `public/` folder when `flex-check-start` is executed on `npm start`.
=> :bug: Remove symlinks to fix #11

packages/flex-plugin/dev_assets/flex.js
`SCENARIO` First time loading Flex from `localhost` with SSO
`GIVEN` I am a developer launching my local version of Flex for the first time with an empty localStorage
`AND` I'm using SSO authentication with Okta
`AND` I've correctly set my URL as a `DEFAULT REDIRECT URL` from the Flex Single Sign-On settings
`WHEN` I'm redirected to the Okta authentication service for performing the login
`AND` after the login has been correctly performed
`THEN` I am redirected back to my original website
`SCENARIO` Second time loading Flex from `localhost` with SSO
`GIVEN` I am a developer launching my local version of Flex for the second time
`AND` I'm using SSO authentication with Okta
`WHEN` I open my browser to my local Flex
`THEN` the LOCAL_FLEX_PLUGIN_FIRST_LOAD key is cleared from my localStorage …
=> Login redirect issue

packages/create-flex-plugin/README.md, packages/create-flex-plugin/__tests__/create-flex-plugin.test.js, packages/create-flex-plugin/src/cli.js, packages/create-flex-plugin/src/create-flex-plugin.js
Removed the admin plugin option as it seemed confusing and would get outdated.  The latest Flex admin dashboard is always available at flex.twilio.com.
=> Removed admin plugin

packages/create-flex-plugin/templates/package.json
core-js@3 is not compatible with @twilio/flex-ui for testing. Thanks to @kjakobson for finding this bug.
=> pin core-js to v2

packages/create-flex-plugin/src/lib/create-flex-plugin.ts
* Checks that the target directory does not exist before creating a new plugin
=> check target path and quit if it exists

changelog/CHANGELOG.md
The initial version of the plugin builder didn't load Flex on `npm start`. This is now the recommended behavior.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> mention .env in migration

packages/create-flex-plugin/templates/js/src/components/CustomTaskList/CustomTaskList.Container.js, packages/create-flex-plugin/templates/ts/src/components/CustomTaskList/CustomTaskList.Container.ts
Generates:
> isOpen: state['signal-demo-test'].customTaskList.isOpen,
instead of
> isOpen: state.signal-demo-test.customTaskList.isOpen,
=> fix regression w/ hyphens in plugin names

packages/create-flex-plugin/src/lib/cli.ts
https://github.com/twilio/flex-plugin-builder/issues/173
- Fix version cli command alias to be `-v` so that `create-flex-plugin -v` and `create-flex-plugin -h` both work as intended.
=> fix version cli command

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
Using rm -rf causes build failure on Windows (when WSL or similar has
not been enabled) rimraf selects a deletion command appropriate for the
local OS.
=> Replace rm -rf by rimraf to improve OS agnosticism

packages/flex-plugin-scripts/src/clients/__tests__/baseClient.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/buildClient.test.ts, packages/flex-plugin-scripts/src/clients/baseClient.ts
* Add `Flex Pluing Builder` as a prefix to the user agent
=> add a base agent name

packages/create-flex-plugin/README.md, packages/create-flex-plugin/src/utils/__tests__/github.test.ts, packages/create-flex-plugin/src/utils/github.ts
* Support `--template` repo to contain source code at the root level instead of `/template` directory as well
=> allow template url to work without template dir as well

packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/commands/flex/plugins/deploy.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
- when an asset version already exists and user does not overwrite, don't upload the new build to serverless and continue registering with plugins api using the existing version
- when an asset version already exists and user does overwrite, overwrite the existing asset in serverless and register the new asset using plugins api
- if on CI, throw an error if an asset version already exists (this is the current behavior)
=> FLEXY-2924 handle asset version collision and prompt user for overwrite

packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step001.ts, packages/flex-plugin-e2e-tests/src/tests/step002.ts, packages/flex-plugin-e2e-tests/src/utils/assertion.ts, packages/flex-plugin-e2e-tests/src/utils/index.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts
* Test `flex:plugins:create` command
=> test for create plugin command

packages/flex-plugin-e2e-tests/src/utils/api.ts, packages/flex-plugins-api-toolkit/package.json, packages/flex-plugins-api-toolkit/src/scripts/__tests__/createConfiguration.test.ts, packages/flex-plugins-api-toolkit/src/scripts/createConfiguration.ts
Enforce load-order for enabling plugins:
* Adding new plugins are appended to the end of the list
* Updating an existing plugin's version updates the plugin _in place_ (preserves the order)
=> Load order create configuration

packages/flex-plugin-scripts/src/prints/fileTooLarge.ts, packages/flex-plugin-scripts/src/scripts/__tests__/build.test.ts, packages/flex-plugin-scripts/src/scripts/build.ts
- CLI Build command to check size of the source map
- CLI Build UTs
- File identifier to `fileTooLarge` 
- UT for checking source map's size
=> Check source map size in build command

packages/flex-plugin-e2e-tests/src/tests/step006.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts
- Removed account sid assert from step006 in E2E tests
=> Remove account sid check in E2E when running flex:plugins:start

packages/flex-plugin-e2e-tests/src/utils/pages/view/base.ts
- Increased default navigation timeout from 30 to 60 seconds
=> Increased page navigation timeout from 30s to 60s

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
Added `react-emotion` to the plugin creation templates. `"react-emotion": "9.2.12"`
=> Flexy-3862

changelog/v6.md
Updated v6 changelog to mention the security fix.
=> Updated v6 changelog

packages/flex-plugin-scripts/src/clients/configurations.ts
The `ConfigurationClient` was missing the attribute that adds support for proxying requests. This results in the `deploy`
failing from clients that are isolated from the network and can reach out only through a proxy.
=> Add proxy support for configuration client

changelog/v6.md, packages/flex-dev-utils/src/logger/lib/__tests__/logger.test.ts, packages/flex-dev-utils/src/logger/lib/logger.ts
When upgrading a plugin from v4- to latest version, as required by current Plugin CLI in order to deploy a plugin that was created in older Plugin CLI versions, we get the following message:
import  _as FlexPlugin from '@twilio/flex-plugin';_
* is being intepreted to change it to italic in console thus i am changing the italic conversion in console from '*' to '?'
=> FLEXY-4359

changelog/v6.md, packages/create-flex-plugin/src/lib/__tests__/commands.test.ts, packages/create-flex-plugin/src/lib/__tests__/create-flex-plugin.test.ts, packages/create-flex-plugin/src/lib/cli.ts, packages/create-flex-plugin/src/lib/commands.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/src/prints/__tests__/finalMessage.test.ts, packages/create-flex-plugin/templates/js2/src/components/CustomTaskList/CustomTaskList.jsx, packages/create-flex-plugin/templates/ts2/src/components/CustomTaskList/CustomTaskList.tsx, packages/flex-plugin-e2e-tests/src/tests/step002.ts, packages/flex-plugin-e2e-tests/src/tests/step005.ts, packages/flex-plugin-e2e-tests/src/utils/pages/view/admin-dashboard.ts
- Plugin CLI should pick FLEX UI 2.x by default
- Both flags (--flexui1 annd flexui2) are intact and by default if none of the switch are used, the CLI will create the plugin using Flex UI 2.x
=> FLEXY-4415 changing to flex ui 2.x by default

.circleci/config.yml, .circleci/configs/e2e_test.yml
Since we started using dynamic configuration, the nightly e2e workflow isn't triggered because it's not in the config.yml. To fix this, we need to make sure the pipeline(generate config) runs daily at 4 pm UTC.
This PR makes the necessary changes trigger the e2e workflow from a  scheduled trigger set in the circle [project settings](https://app.circleci.com/settings/project/github/twilio/flex-plugin-builder/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Ftwilio%2Fflex-plugin-builder&triggerSource=&scheduledTriggerId=1c4b6306-92f7-4a2a-8d9b-cb928ef43ca5&success=true). We are introducing a new pipeline parameter which will be passed from the settings and it will run the e2e nightly workflow. we are also sending run_pr_validator parameter with the value false(default …
=> FLEXY-4620 Update e2e triggers

.circleci/configs/e2e_test.yml, .circleci/configs/pr_validator.yml
Updated macos resource class since `medium` is getting deprecated on Oct 2, 2023.
=> FLEXY-4758 Updated macos resource class

.github/workflows/pr_e2e.yaml, changelog/v6.md, package-lock.json, packages/flex-plugin-e2e-tests/src/tests/step010.ts, packages/flex-plugin-e2e-tests/src/tests/step011.ts, packages/flex-plugin-e2e-tests/src/tests/step012.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts, packages/flex-plugin-webpack/package.json, packages/flex-plugin-webpack/src/compiler.ts, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts, packages/flex-plugin-webpack/src/devServer/pluginServer.ts
--include-remote flag in flex:plugins:start command is broken as a side-effect of the fix released for the third-party cookie phase-out by Google Chrome. Since 3rd party cookies are going to be blocked by default, Flex is now using partitioned cookies for authentication. In localhost, partitioned cookies are inaccessible hence, the remote plugins were failing to load.
With this fix, the remote plugins will be loaded via webpack dev server middleware which will call Flex endpoint by authenticating the request using the X-Flex-JWE header.
=> Fix for loading remote plugins in localhost

.github/workflows/~reusable_public_publish.yaml, bin/publish, packages/create-flex-plugin/package-lock.json, packages/create-flex-plugin/package.json, packages/flex-dev-utils/package-lock.json, packages/flex-dev-utils/package.json, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-test/package.json, packages/flex-plugin-utils-jest/package.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugin-webpack/package.json, packages/flex-plugin/package.json, packages/flex-plugins-api-client/package-lock.json, packages/flex-plugins-api-client/package.json, packages/flex-plugins-utils-env/package-lock.json, packages/flex-plugins-utils-env/package.json, packages/flex-plugins-utils-exception/package.json, packages/plugin-flex/README.md, packages/plugin-flex/package-lock.json, packages/plugin-flex/package.json
Fixed package and package-lock for all the packages
=> v6.3.3 Fixed package and package-lock for all the packages

packages/flex-dev-utils/src/logger/lib/__tests__/logger.test.ts, packages/flex-dev-utils/src/logger/lib/logger.ts, packages/flex-plugin-scripts/src/prints/validateSuccessful.ts
Added support for logging without markdown and used the new `log` method in validation report logs.
=> Added support for logging without markdown

packages/flex-plugin-scripts/src/scripts/validate.ts, packages/plugin-flex/package.json, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/configuration.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin-version.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/build.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/create-configuration.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/describe/configuration.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/describe/plugin-version.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/describe/plugin.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/describe/release.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/diff.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/list/configurations.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/list/plugin-versions.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/list/plugins.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/list/releases.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/release.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/test.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/validate.test.ts, packages/plugin-flex/src/commands/flex/plugins/list/configurations.ts
- Improved unit test patch coverage
- Capture and display validation error message, if present
- Updated --bypass-validation flag description
=> Validate error message handling and test coverage improvement

packages/create-flex-plugin/templates/js2/package.json, packages/create-flex-plugin/templates/ts2/package.json, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts, packages/flex-plugin-webpack/src/devServer/pluginServer.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts
The --include-remote did not work when token size increased beyond browser limit failing the plugins load. This PR fixes that
=> FLEXY-5303 Token size issue when fetching remote plugins

.github/workflows/~reusable_e2e_by_OS.yaml
Adding `taskkill` for Windows E2E tests to ensure that the tests are killed after the timeout period.
=> Add task kill for windows E2E

.github/workflows/skip_pr_workflow.yaml
=> FLEXY-5434 added skip workflow

.github/workflows/e2e_scheduled.yaml, .github/workflows/pr_e2e.yaml, .github/workflows/pr_workflow.yaml, .github/workflows/skip_e2e.yaml, .github/workflows/skip_pr_workflow.yaml, .github/workflows/skip_publish.yaml, .github/workflows/tag.yaml, .github/workflows/~reusable_e2e_all_OS.yaml, .github/workflows/~reusable_e2e_by_OS.yaml, .github/workflows/~reusable_public_publish.yaml, .github/workflows/~reusable_publish.yaml
=> Update ubuntu os version

.github/workflows/~reusable_e2e_by_OS.yaml
E2E nightly failing with Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> remove deprecated version of `actions/upload-artifact: v3`
