twilio/flex-plugin-builder

packages/flex-plugin/dev_assets/index.html
Add 'no-referrer' meta tag which is W3C standard value to index.html.
=> Add <meta name="referrer" content="no-referrer"> to index.html

packages/create-flex-plugin/package.json
While https://github.com/standard-things/esm/issues/720 is open this should fix the problem. Once that is addressed we should fix it properly based on the outcome.
=> :bug: Fix #37 by pinning version of create-flex-plugin

packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/create-flex-plugin.js, packages/react-app-rewire-flex-plugin/lib/index.js
- get cdn version from installed flex-ui package.json
- cleanup unused imports
- bump admin plugin version to 1.0.1
=> Install latest v1 flex-ui by default

packages/create-flex-plugin/__tests__/lib/create-flex-plugin.test.ts, packages/create-flex-plugin/__tests__/utils/validators.test.ts, packages/create-flex-plugin/src/lib/cli.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/create-flex-plugin/templates/package.json
* Fix the duplicate alias for the CLI args
* Check accountSid is valid when provided via CLI
* More testing
=> fix the cli and add a bit more testing for validation

jest.config.js, package.json, packages/create-flex-plugin/package.json, packages/flex-plugin/package.json
* Bumps packages to the latest version
=> bump modules to the latest

packages/create-flex-plugin/src/dependencies.json, packages/create-flex-plugin/src/lib/commands.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/templates/package.json, packages/create-flex-plugin/templates/src/DemoPlugin.js, packages/create-flex-plugin/templates/src/components/CustomTaskListComponent.js
* Add craco-config version
* Cleanup the templates js structure
=> cleanup template and add craco-config version

.travis.yml, package.json
* Do not use CI for building
* Add dev branch to list of build validation
=> update travis and lerna to not use ci

packages/craco-config-flex-plugin/index.js, packages/craco-config-flex-plugin/lib/devServer.js, packages/craco-config-flex-plugin/lib/webpack.js, packages/craco-config-flex-plugin/package.json
* Only output the bundle and map to `build` directory
=> only output bundle and map

packages/create-flex-plugin/src/lib/cli.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/templates/ts/package.json, packages/create-flex-plugin/templates/ts/src/DemoPlugin.tsx, packages/create-flex-plugin/templates/ts/src/components/CustomTaskListComponent.tsx, packages/create-flex-plugin/templates/ts/src/index.ts, packages/create-flex-plugin/templates/ts/tsconfig.json, packages/create-flex-plugin/tsconfig.json, packages/create-flex-plugin/tslint.json
=> support typescript

README.md
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> update changelog link

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json, packages/flex-plugin/README.md
* Flex-UI currently only supports React 16.5.2.
=> pin the react versions

package.json, packages/create-flex-plugin/tsconfig.json, packages/flex-plugin/package.json, packages/flex-plugin/tsconfig.json
* Add prebuild to clear dist
* Add `__mocks__` to exclude
=> fix the exclude paths

packages/flex-plugin/README.md, packages/flex-plugin/package.json, packages/flex-plugin/src/index.ts, packages/flex-plugin/src/utils/__tests__/loadCSS.test.ts, packages/flex-plugin/src/utils/__tests__/loadJS.test.ts, packages/flex-plugin/src/utils/loadCSS.ts, packages/flex-plugin/src/utils/loadJS.ts
- Add helper methods `loadJS` and `loadCSS` to load external JS/CSS files.
- Add tests for the helper methods.
- Update README to include a Utilities section.
=> Helper methods for loading external JS/CSS files

packages/craco-config-flex-plugin/package.json, packages/craco-config-flex-plugin/src/config/webpack.ts
* adds the missing `clean-webpack-plugin` package
=> add missing package

package.json
=> GitHub hooks

packages/craco-config-flex-plugin/README.md, packages/flex-dev-utils/README.md, packages/flex-dev-utils/jest.config.js, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/logger.ts, packages/flex-dev-utils/src/ora.ts, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-dev-utils/tsconfig.json
* Flex-dev-utils to contain all common utility files
=> add flex-dev-utils

jest.config.base.js, jest.config.js, packages/craco-config-flex-plugin/jest.config.js, packages/craco-config-flex-plugin/package.json, packages/craco-config-flex-plugin/tsconfig.json, packages/create-flex-plugin/jest.config.js, packages/create-flex-plugin/package.json, packages/create-flex-plugin/tsconfig.json, packages/flex-dev-utils/jest.config.js, packages/flex-dev-utils/package.json, packages/flex-dev-utils/tsconfig.json, packages/flex-plugin-scripts/jest.config.js, packages/flex-plugin-scripts/tsconfig.json, packages/flex-plugin/jest.config.js, packages/flex-plugin/package.json, packages/flex-plugin/tsconfig.json, tsconfig.json
* Update tsconfig and jest.config to remove duplicate test and simplify exclude
=> Jest tsconfig fixes

package.json, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/release.test.ts, packages/flex-plugin/dev_assets/flex.test.ts, tsconfig.lint.json
* Run linter on test files too
=> run lint on test files too

packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/__tests__/logger.test.ts, packages/flex-plugin-scripts/package.json, packages/flex-plugin-scripts/src/prints/availabilityWarning.ts
* Testing removal of packages used in flex-dev-utils
=> checking lerna bootstrap

packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/index.ts, packages/create-flex-plugin/src/lib/cli.ts, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-plugin-scripts/src/index.ts
* Run `update-notifier` to check for updates
=> notify for update

packages/flex-plugin/README.md
* Specify the external dependencies and add documentation about not bumping these values.
=> update readme about react-version

packages/create-flex-plugin/src/prints/finalMessage.ts, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-plugin-scripts/src/prints/availabilityWarning.ts
=> add docblock

packages/create-flex-plugin/src/utils/__tests__/validators.test.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/flex-dev-utils/src/__tests__/sids.test.ts, packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/sids.ts
=> Use flex dev utils sids

packages/flex-plugin-scripts/src/clients/environments.ts, packages/flex-plugin-scripts/src/utils/__tests__/runtime.test.ts, packages/flex-plugin-scripts/src/utils/paths.ts, packages/flex-plugin-scripts/src/utils/runtime.ts
* Deploy each plugin to its Environment
=> One env per plugin

packages/flex-plugin/README.md
=> update readme to match support docs

.travis.yml, codecov.yml, jest.config.base.js, package.json, packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/utils/__tests__/__snapshots__/logging.test.ts.snap, packages/flex-plugin/package.json
* Adds coverage report publication to codecov
=> add coverage report

package.json, packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/utils/__tests__/__snapshots__/logging.test.ts.snap, packages/flex-plugin/package.json
Forces the use of `--color` even if the terminal does not support coloring
=> fix snapshot coloring fix

packages/craco-config-flex-plugin/README.md, packages/craco-config-flex-plugin/package.json, packages/craco-config-flex-plugin/src/config/__tests__/jest.test.ts, packages/craco-config-flex-plugin/src/config/devServer.ts, packages/craco-config-flex-plugin/src/config/jest.ts, packages/craco-config-flex-plugin/src/config/webpack.ts, packages/craco-config-flex-plugin/src/index.ts, packages/craco-config-flex-plugin/src/utils/fs.ts, packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
* Add coverage report function
* Add support for *.config.js support
* Add jest
=> add jest, and support for reading from *.config.js files

packages/craco-config-flex-plugin/src/config/__tests__/devServer.test.ts, packages/craco-config-flex-plugin/src/config/__tests__/webpack.test.ts, packages/craco-config-flex-plugin/src/utils/__tests__/fs.test.ts
=> add a few more tests

packages/flex-dev-utils/src/__tests__/keytar.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/services.test.ts, packages/flex-plugin-scripts/src/clients/services.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/release.test.ts, packages/flex-plugin-scripts/src/scripts/release.ts
* No versioning; all releases will be to version `0.0.0` and overwrite the existing version
* If no service exists, then create one
=> do not support versioning for now

packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/package.json, packages/create-flex-plugin/src/lib/commands.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json, packages/flex-plugin-scripts/package.json
* Removes jest from deps
* Adds flex-plugin-scripts to template
=> add flex-plugin-scripts to package.json

packages/flex-dev-utils/src/__tests__/keytar.test.ts, packages/flex-dev-utils/src/keytar.ts, packages/flex-plugin-scripts/package.json, packages/flex-plugin-scripts/src/clients/assets.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/clients/services.ts, packages/flex-plugin-scripts/src/utils/__tests__/runtime.test.ts
Use the new serverless upload api
=> use the new upload api

packages/flex-plugin-scripts/src/clients/assets.ts, packages/flex-plugin-scripts/src/clients/files.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/clients/serverless-types.ts
* Refactor Assets client into Files client in preparation for future Function implementation
=> refactor assets to files

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json, packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts
=> renaming release to deploy

packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/docs/list.md, packages/flex-plugin-scripts/docs/start.md
=> update docs, and autogenerate the readme

packages/flex-dev-utils/src/__tests__/inquirer.test.ts, packages/flex-dev-utils/src/inquirer.ts, packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/docs/remove.md, packages/flex-plugin-scripts/src/clients/__tests__/environment.test.ts, packages/flex-plugin-scripts/src/clients/environments.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/scripts/__tests__/remove.test.ts, packages/flex-plugin-scripts/src/scripts/remove.ts, packages/flex-plugin-scripts/src/utils/runtime.ts
Adds a remove script to delete the plugin
=> Remove script

bin/publish
=> add publish script

bin/publish
Quit script if any of the scripts fail
=> update publish script to exit if script fails

packages/flex-plugin-scripts/src/clients/__tests__/environment.test.ts, packages/flex-plugin-scripts/src/clients/environments.ts, packages/flex-plugin-scripts/src/utils/__tests__/require.test.ts
* DomainSuffix is now required
=> post the domain-suffix as well

packages/flex-plugin-scripts/src/clients/__tests__/build.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/deployment.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/environment.test.ts, packages/flex-plugin-scripts/src/clients/builds.ts, packages/flex-plugin-scripts/src/clients/deployments.ts, packages/flex-plugin-scripts/src/clients/environments.ts, packages/flex-plugin-scripts/src/clients/services.ts
=> add more tests

package.json, packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/package.json, packages/flex-dev-utils/package.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin/package.json
* Remove all-contributor script
* Remove typescript from each package
=> remove typescript from package.json

packages/craco-config-flex-plugin/src/config/__tests__/webpack.test.ts, packages/craco-config-flex-plugin/src/config/webpack.ts
=> fix ref to shim file

bin/publish, packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/package.json, packages/flex-dev-utils/package.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin/package.json
=> add rm dist script

jest.config.base.js, packages/flex-dev-utils/src/__tests__/logger.test.ts, packages/flex-dev-utils/src/__tests__/prints.test.ts, packages/flex-dev-utils/src/__tests__/spawn.test.ts, packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/logger.ts, packages/flex-dev-utils/src/prints.ts, packages/flex-dev-utils/src/spawn.ts, packages/flex-plugin-scripts/src/prints/appConfigMissing.ts, packages/flex-plugin-scripts/src/prints/expectedDependencyNotFound.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/prints/instructionToReinstall.ts, packages/flex-plugin-scripts/src/prints/preFlightByPass.ts, packages/flex-plugin-scripts/src/prints/publicDirCopyFailed.ts, packages/flex-plugin-scripts/src/prints/versionMismatch.ts, packages/flex-plugin-scripts/src/scripts/__tests__/check-start.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/utils/run.ts
* Better error message display to the user
* Warn user if they are using a different version of react/react-dom
=> Pre flight package check

packages/create-flex-plugin/src/lib/commands.ts, packages/flex-dev-utils/src/__tests__/spawn.test.ts, packages/flex-dev-utils/src/spawn.ts, packages/flex-plugin-scripts/flex-plugin-scripts, packages/flex-plugin-scripts/src/scripts/__tests__/clear.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/clear.ts, packages/flex-plugin-scripts/src/utils/__tests__/runtime.test.ts
* Make all returned values of `spawn` non-null
=> Empty string for spawn

packages/craco-config-flex-plugin/README.md
Update readme to explain the difference between craco.config and webpack.config file.
=> readme update

packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/open.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/sub/browser.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/scripts/sub/browser.ts
Makes the port of /plugins.json dynamic
=> dynamic plugins url

packages/flex-plugin-scripts/src/clients/__tests__/buildClient.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/configuration.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/http.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/services.test.ts, packages/flex-plugin-scripts/src/clients/baseClient.ts, packages/flex-plugin-scripts/src/clients/configuration-types.ts, packages/flex-plugin-scripts/src/clients/configurations.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/clients/index.ts, packages/flex-plugin-scripts/src/clients/services.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/utils/__tests__/runtime.test.ts, packages/flex-plugin-scripts/src/utils/runtime.ts
* Register service sid with Configuration service
=> register sid in configuration service

packages/flex-plugin-scripts/src/scripts/deploy.ts
=> fix sourcemap path

packages/craco-config-flex-plugin/package.json, packages/craco-config-flex-plugin/src/config/__tests__/webpack.test.ts, packages/craco-config-flex-plugin/src/config/webpack.ts
=> sourcemap bundle path

packages/flex-plugin-scripts/dev_assets/index.html
=> flex bundle uri

jest.config.js, packages/craco-config-flex-plugin/src/config/__tests__/webpack.test.ts, packages/create-flex-plugin/src/lib/commands.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-plugin-scripts/src/clients/__tests__/files.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/http.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-scripts/src/utils/run.ts
* Add min threshold of 90
* Add enough test to get to 90 😂 😢 😭 😭
=> add min coverage of 90

packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/src/lib/__tests__/cli.test.ts, packages/create-flex-plugin/src/lib/cli.ts, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/src/utils/__tests__/validators.test.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/flex-plugin-scripts/dev_assets/flex.js, packages/flex-plugin-scripts/dev_assets/flex.test.ts
=> remove account sid as a requirement

packages/create-flex-plugin/src/utils/__tests__/validators.test.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/flex-dev-utils/src/__tests__/credentials.test.ts, packages/flex-dev-utils/src/__tests__/errors/FlexPluginError.test.ts, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/credentials.ts, packages/flex-dev-utils/src/errors/FlexPluginError.ts, packages/flex-dev-utils/src/errors/index.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/list.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/sub/browser.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/scripts/list.ts, packages/flex-plugin-scripts/src/scripts/remove.ts, packages/flex-plugin-scripts/src/scripts/sub/browser.ts, packages/flex-plugin-scripts/src/utils/__tests__/paths.test.ts, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-scripts/src/utils/paths.ts, packages/flex-plugin-scripts/src/utils/run.ts
=> Error handling

packages/flex-plugin-scripts/src/__tests__/index.test.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/prints/cracoConfigMissing.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/check-start.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/utils/run.ts
* Check for craco-config.js 
* Exit if any of the scripts fail
=> check for craco.config

packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
=> bump the template version

changelog/v3.md
=> changelog v3

packages/create-flex-plugin/src/prints/__tests__/__snapshots__/finalMessage.test.ts.snap, packages/create-flex-plugin/src/prints/finalMessage.ts
* Adds a deploy command to the final message
=> Update final message

packages/create-flex-plugin/src/lib/create-flex-plugin.ts
=> do not use finally

packages/create-flex-plugin/src/lib/__tests__/cli.test.ts, packages/create-flex-plugin/src/lib/cli.ts, packages/flex-dev-utils/src/runner.ts
* await for scripts to run
* Then exit
=> exit when create-plugin ends

packages/flex-plugin-scripts/src/clients/__tests__/accounts.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/assets.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/buildClient.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/configuration.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/services.test.ts, packages/flex-plugin-scripts/src/clients/account-types.ts, packages/flex-plugin-scripts/src/clients/accounts.ts, packages/flex-plugin-scripts/src/clients/baseClient.ts, packages/flex-plugin-scripts/src/clients/builds.ts, packages/flex-plugin-scripts/src/clients/configurations.ts, packages/flex-plugin-scripts/src/clients/services.ts, packages/flex-plugin-scripts/src/prints/deploySuccessful.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts
* Add a new successful message:
=> Success message

packages/create-flex-plugin/src/lib/__tests__/commands.test.ts, packages/create-flex-plugin/src/lib/commands.ts, packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/dev_assets/index.html, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start/browser.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start/pluginServer.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/scripts/start/browser.ts, packages/flex-plugin-scripts/src/scripts/start/pluginServer.ts, packages/flex-plugin-scripts/src/scripts/start/server.ts
* Support for enabling live plugins to run locally
=> support for live plugins

packages/flex-plugin-scripts/src/__tests__/index.test.ts, packages/flex-plugin-scripts/src/scripts/start/pluginServer.ts, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-scripts/src/utils/run.ts
* Fix issue with `npm run test` and others not exiting when script fails.
=> fix exit issues

packages/flex-dev-utils/src/__tests__/logger.test.ts, packages/flex-dev-utils/src/logger.ts, packages/flex-dev-utils/src/ora.ts, packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/src/clients/__tests__/buildClient.test.ts, packages/flex-plugin-scripts/src/clients/baseClient.ts, packages/flex-plugin-scripts/src/clients/builds.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/scripts/remove.ts, packages/flex-plugin-scripts/src/scripts/start.ts
Add/enable support for `DEBUG=1` and `TRACE=1` level logs
=> debug mode

packages/flex-dev-utils/src/credentials.ts
* Add keytar require error to debug level
=> add keytar log

packages/create-flex-plugin/README.md
The sample commands do not specify a plugin name. Copying and pasting this command will result in an error.
Small correction to the README
=> Correct command in `Version Support` section

.travis.yml, packages/flex-plugin-scripts/src/clients/__tests__/buildClient.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/http.test.ts, packages/flex-plugin-scripts/src/clients/baseClient.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/prints/packagesVersions.ts, packages/flex-plugin-scripts/src/scripts/__tests__/info.test.ts, packages/flex-plugin-scripts/src/scripts/info.ts, packages/flex-plugin-scripts/src/utils/package.ts
- Include versions of installed flex plugin builder core dependencies in user agent for aiding support, operations, and feature prioritization.
=> FLEXY-1681 include flex package info in user agent

.travis.yml, packages/flex-plugin-scripts/src/clients/baseClient.ts, packages/flex-plugin-scripts/src/scripts/info.ts, packages/flex-plugin-scripts/src/utils/package.ts, packages/flex-plugin-scripts/src/utils/require.ts
- Remove unused hijack/require
- bug: importing flex_packages invokes info command
- reset node heap
=> FLEXY-1681 remove unused hijack/require

lerna.json, packages/create-flex-plugin/package.json, packages/flex-plugin-scripts/package.json
Bump lerna.json + package.jsons
=> Bump to v3.4.0

packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
Fixes the issue https://github.com/twilio/flex-plugin-builder/issues/219
=> fix the issue 219

packages/flex-dev-utils/src/__tests__/logger.test.ts, packages/flex-dev-utils/src/logger.ts
Change background color of names to magenta see it shows on white background as well
=> change the color

packages/create-flex-plugin/templates/ts/src/states/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start/server.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/scripts/start/server.ts
* Fix PORT env variable not being respected (Issue https://github.com/twilio/flex-plugin-builder/issues/221)
* Fix redux state TS typing (Issue https://github.com/twilio/flex-plugin-builder/issues/230)
=> fix passing PORT as env var; fix typescript definition

packages/craco-config-flex-plugin/src/config/__tests__/webpack.test.ts, packages/craco-config-flex-plugin/src/config/webpack.ts, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/__tests__/require.test.ts, packages/flex-dev-utils/src/require.ts
=> bundle css

packages/flex-dev-utils/src/env.ts, packages/flex-dev-utils/src/paths.ts, packages/flex-plugin-scripts/package.json, packages/flex-plugin-scripts/src/config/index.ts, packages/flex-plugin-scripts/src/config/jest.config.ts, packages/flex-plugin-scripts/src/config/jestTransforms/babel.ts, packages/flex-plugin-scripts/src/config/jestTransforms/css.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/prints/jestNotInstalled.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/scripts/list.ts, packages/flex-plugin-scripts/src/scripts/remove.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/scripts/test.ts, packages/flex-plugin-scripts/src/scripts/test/test.ts
=> add testing config

jest.config.base.js, packages/flex-dev-utils/src/logger.ts, packages/flex-dev-utils/src/urls.ts, packages/flex-plugin-scripts/src/config/__tests__/jest.config.test.ts, packages/flex-plugin-scripts/src/config/jest.config.ts, packages/flex-plugin-scripts/src/config/webpack.dev.ts, packages/flex-plugin-scripts/src/scripts/__tests__/build.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/test.test.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/scripts/test.ts, packages/flex-plugin-scripts/src/scripts/test/test.ts, packages/flex-plugin-scripts/src/types.d.ts, packages/flex-plugin-scripts/src/utils/compiler.ts
* Test coverage for webpack refactor work
=> webpack test coverage

changelog/v2.md, changelog/v3.md
- remove recommendation to install create-flex-plugin globally
- reorder scripts and use rimraf
- clarify the need to remove v1 assets
=> update migration guides

packages/flex-dev-utils/src/__tests__/errors/UserActionError.test.ts, packages/flex-dev-utils/src/errors/UserActionError.ts, packages/flex-dev-utils/src/errors/index.ts, packages/flex-plugin-scripts/src/clients/__tests__/configurations.test.ts, packages/flex-plugin-scripts/src/clients/configuration-types.ts, packages/flex-plugin-scripts/src/clients/configurations.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/utils/require.ts
* Check ui_dependencies when doing a deploy for react-compatibility
=> Configuration react unbundled

packages/flex-plugin-scripts/src/clients/__tests__/configurations.test.ts, packages/flex-plugin-scripts/src/clients/configuration-types.ts, packages/flex-plugin-scripts/src/clients/configurations.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts
Check Configuration if deploying unbundled react and verify flex-ui is compatible
=> check configuration for flex-ui version

packages/flex-plugin-scripts/src/scripts/deploy.ts
* Change warning messages and link to appropriate pages to change settings
=> change warning messages

packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/prints/loadPluginCountError.ts, packages/flex-plugin-scripts/src/scripts/__tests__/check-start.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts
* Check how many `FlexPlugin.loadPlugin` is called and disallow it if more than 1 is called
=> count the number of loadPlugin calls

packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/info.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts
Check for jsx and tsx files as well
=> Fix check start

packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/env.ts, packages/flex-plugin-scripts/src/clients/serverless-types.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/scripts/list.ts, packages/flex-plugin-scripts/src/scripts/remove.ts, packages/flex-plugin-scripts/src/utils/runtime.ts
* Quiet mode in plugin-builder
=> add quiet mode

packages/flex-plugin-scripts/dev_assets/index.html, packages/flex-plugin-scripts/src/config/__tests__/webpack.config.test.ts, packages/flex-plugin-scripts/src/config/webpack.config.ts
Fix regression causd by merging with master
=> fix local server

packages/flex-dev-utils/src/__tests__/urls.test.ts, packages/flex-dev-utils/src/urls.ts, packages/flex-plugin-scripts/src/config/__tests__/devServer/pluginServer.test.ts, packages/flex-plugin-scripts/src/config/devServer/pluginServer.ts, packages/flex-plugin-scripts/src/config/webpack.dev.ts, packages/flex-plugin-scripts/src/prints/devServerSuccessful.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/utils/compiler.ts
=> move dev-server into webpack

packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/__tests__/require.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/require.ts, packages/flex-plugin-scripts/src/config/webpack.config.ts, packages/flex-plugin-scripts/src/scripts/__tests__/check-start.test.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts, packages/flex-plugin-scripts/src/scripts/start.ts
* Add support for `--core-cwd` which will be used by the twilio cli 
* Also use internal index.html instead of copying over the index.html to `public/` directory
=> add a core cwd

packages/flex-plugin-scripts/src/__tests__/index.test.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-scripts/src/utils/run.ts
=> Fix spawn require

packages/flex-dev-utils/src/fs.ts
* Use require.resolve to determine path to flex-plugin-scripts
=> bump latest packages

packages/flex-plugin-scripts/src/config/compiler.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts
=> add support to spawn scripts

.travis.yml, packages/flex-plugin-scripts/package.json, packages/flex-plugin-scripts/src/config/__tests__/devServer/ipcServer.test.ts, packages/flex-plugin-scripts/src/config/compiler.ts, packages/flex-plugin-scripts/src/config/devServer/ipcServer.ts, packages/flex-plugin-scripts/src/config/devServer/webpackDevServer.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts
=> add ipc server

packages/flex-plugin-scripts/src/scripts/__tests__/check-start.test.ts, packages/flex-plugin-scripts/src/scripts/check-start.ts
=> moved checkPluginConfiguration up

packages/flex-dev-utils/__mocks__/keytar.ts, packages/flex-dev-utils/src/__tests__/credentials.test.ts, packages/flex-dev-utils/src/credentials.ts
=> Fixes credentials bug with CI/api key/secret

packages/craco-config-flex-plugin/package.json, packages/create-flex-plugin/package.json, packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json, packages/flex-dev-utils/package.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin/package.json
* Bump packages to fix issues (update keytar to latest version as well)
* Fix version corruption for lerna that was causing incorrect versions for the packages
=> bump packages and fix versions

packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/src/config/__tests__/devServer/pluginServer.test.ts, packages/flex-plugin-scripts/src/config/devServer/webpackDevServer.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts
=> cleanup unused code

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json
* remove scripts - will use twilio cli instead
=> remove scripts from template

bin/publish, package.json
=> publish update script

packages/create-flex-plugin/templates/js/package.json, packages/create-flex-plugin/templates/ts/package.json, packages/flex-plugin-scripts/docs/check-start.md, packages/flex-plugin-scripts/docs/pre-script-check.md, packages/flex-plugin-scripts/docs/pre-start-check.md, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-start-check.test.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts, packages/flex-plugin-scripts/src/scripts/pre-start-check.ts, packages/flex-plugin/bin/check-start, packages/flex-plugin/package.json
* Remove legacy code from v1
* Separate out check-start into `pre-script-check` and `pre-start-check`
=> remove appConfig check from all apps

packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts
* Overwrite plugin inside ~/.twilio-cli
=> remove confirm of multi-plugin

changelog/v4.md, jest.config.base.js, packages/create-flex-plugin/templates/core/jest.config.js, packages/create-flex-plugin/templates/core/webpack.config.js, packages/create-flex-plugin/templates/core/webpack.dev.js, packages/flex-plugin-scripts/README.md, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts
* Add a WIP changelog
* Add config.js template to create-plugin
=> add changelog and the templates

packages/create-flex-plugin/templates/core/public/appConfig.example.js, packages/create-flex-plugin/templates/core/public/appConfig.js
=> change the loglevel to info

packages/flex-plugin-webpack/LICENSE, packages/flex-plugin-webpack/README.md, packages/flex-plugin-webpack/docs.config.js, packages/flex-plugin-webpack/jest-preset.js, packages/flex-plugin-webpack/jest.config.js, packages/flex-plugin-webpack/package.json, packages/flex-plugin-webpack/tsconfig.json
=> add webpack boilerplate as a package

.travis.yml, packages/create-flex-plugin/templates/js/src/DemoPlugin.js, packages/create-flex-plugin/templates/ts/src/DemoPlugin.tsx, packages/flex-plugin-scripts/package.json, packages/flex-plugin-test/package.json, packages/flex-plugin-webpack/package.json
* Require Node 10 and above
* Fix duplicate React keys
* Run Travis on node 10/12/14/lts/stable
=> Minor fixes

.gitignore, .npmrc, lerna.json, package-lock.json, package.json, packages/create-flex-plugin/package-lock.json, packages/flex-dev-utils/package-lock.json, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugin/package-lock.json
=> add the lockfile

changelog/v4.md, packages/flex-plugin-scripts/package.json
* Update changelog
* Remove peerDeps
=> changelog update

lerna.json, packages/create-flex-plugin/package-lock.json, packages/create-flex-plugin/package.json, packages/flex-dev-utils/package-lock.json, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-test/package.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugin-webpack/package.json, packages/flex-plugin-webpack/src/webpack/webpack.config.ts
* React/react-dom/flex-ui should always be read from cwd node_modules
=> fix checking react/react-dom/flex-ui versions

packages/flex-plugin-webpack/src/webpack/webpack.config.ts
* Style-loader should always be present
=> Style loader

packages/create-flex-plugin/src/lib/__tests__/create-flex-plugin.test.ts, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts
* Reset plugin directory if it changes
=> Fix changing plugin directory

packages/flex-dev-utils/src/fs.ts
=> update prompt message

packages/flex-plugin-scripts/src/scripts/__tests__/build.test.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-test/src/index.ts
* Bump version before building
=> update plugin version pre-build

.eslintrc, packages/create-flex-plugin/src/lib/create-flex-plugin.ts, packages/create-flex-plugin/src/utils/github.ts, packages/flex-dev-utils/src/credentials.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/urls.ts, packages/flex-dev-utils/src/validators.ts, packages/flex-plugin-scripts/src/clients/__tests__/builds.test.ts, packages/flex-plugin-scripts/src/clients/builds.ts, packages/flex-plugin-scripts/src/clients/serverless-types.ts, packages/flex-plugin-scripts/src/prints/buildFailure.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-webpack/src/devServer/ipcServer.ts
* Part two of linting: removing `"no-use-before-define": "off"`
=> more linting

packages/flex-dev-utils/package.json, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-scripts/src/utils/run.ts
* Bump axios to fix the vulnerability
=> bump axios

package-lock.json, package.json, packages/flex-dev-utils/package-lock.json, packages/flex-dev-utils/package.json
=> Bump package

.travis.yml, packages/create-flex-plugin/src/utils/__tests__/github.test.ts, packages/create-flex-plugin/src/utils/__tests__/validators.test.ts, packages/flex-dev-utils/src/__tests__/env.test.ts, packages/flex-dev-utils/src/__tests__/errors/UserActionError.test.ts, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/__tests__/keychain.test.ts, packages/flex-dev-utils/src/__tests__/validators.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-builder-toolkit/src/scripts/__tests__/start.test.ts, packages/flex-plugin-builder-toolkit/src/scripts/start.ts, packages/flex-plugin-scripts/src/__tests__/index.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/environments.test.ts, packages/flex-plugin-scripts/src/clients/__tests__/http.test.ts, packages/flex-plugin-scripts/src/clients/http.ts, packages/flex-plugin-scripts/src/scripts/__tests__/build.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/list.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-start-check.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/utils/__tests__/parser.test.ts, packages/flex-plugin-scripts/src/utils/__tests__/run.test.ts, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts
=> linting with sonarjs rules

packages/create-flex-plugin/src/lib/cli.ts, packages/create-flex-plugin/src/utils/__tests__/validators.test.ts, packages/create-flex-plugin/src/utils/validators.ts, packages/flex-dev-utils/src/__tests__/validators.test.ts, packages/flex-dev-utils/src/validators.ts
* Remove the requirement of plugin- prefix
=> remove the plugin- prefix requirement

packages/plugin-flex/src/__tests__/commands/flex/plugins/describe/configuration.test.ts, packages/plugin-flex/src/commands/flex/plugins/describe/configuration.ts, packages/plugin-flex/src/commands/flex/plugins/describe/plugin-version.ts, packages/plugin-flex/src/commands/flex/plugins/describe/plugin.ts, packages/plugin-flex/src/commands/flex/plugins/describe/release.ts, packages/plugin-flex/src/commands/flex/plugins/list/configurations.ts, packages/plugin-flex/src/commands/flex/plugins/list/plugin-versions.ts, packages/plugin-flex/src/commands/flex/plugins/list/plugins.ts, packages/plugin-flex/src/commands/flex/plugins/list/releases.ts
* Check Travis
* Check codecov status report
=> check why travis build status is not reported

.travis.yml, bin/nightly.sh
* Script for doing a nightly build
=> Nightly builds

package-lock.json, package.json, packages/create-flex-plugin/package.json, packages/flex-dev-utils/package.json, packages/flex-plugin-builder-toolkit/package.json, packages/flex-plugin-scripts/package.json, packages/flex-plugin-test/package.json, packages/flex-plugin-webpack/package.json, packages/flex-plugin/package.json, packages/plugin-flex/package.json
=> update package.json to use specifically tsc from root module

.travis.yml, bin/dev.sh, bin/nightly.sh, bin/publish, packages/plugin-flex/bin/prepack
=> add a dev build

packages/plugin-flex/src/sub-commands/flex-plugin.ts
=> export the profile from current user

bin/dev.sh, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/configuration.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin-version.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin.test.ts, packages/plugin-flex/src/commandDocs.json, packages/plugin-flex/src/commands/flex/plugins/archive/configuration.ts, packages/plugin-flex/src/commands/flex/plugins/archive/plugin-version.ts, packages/plugin-flex/src/commands/flex/plugins/archive/plugin.ts, packages/plugin-flex/src/commands/flex/plugins/build.ts, packages/plugin-flex/src/prints/archiveResource.ts, packages/plugin-flex/src/sub-commands/archive-resource.ts
=> fix archive bugs

packages/plugin-flex/src/commands/flex/plugins/deploy.ts, packages/plugin-flex/src/commands/flex/plugins/describe/release.ts, packages/plugin-flex/src/commands/flex/plugins/release.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Set PERSIST_TERMINAL=true when running in debug mode.
=> persist the terminal when running in debug mode

.circleci/config.yml
- CircleCI configuration with a PR validator job to run unit tests and linter on node versions: 10, 12, 14, LTS in a matrix configuration.
- Codecov integration
=> Added Circle CI PR validator job

packages/flex-plugin-webpack/jest.config.js, packages/flex-plugin-webpack/package.json, packages/flex-plugin-webpack/src/prints/dotEnvIncorrectVariable.ts, packages/flex-plugin-webpack/src/prints/index.ts, packages/flex-plugin-webpack/src/webpack/__tests__/clientVariables.test.ts, packages/flex-plugin-webpack/src/webpack/__tests__/webpack.config.test.ts, packages/flex-plugin-webpack/src/webpack/clientVariables.ts, packages/flex-plugin-webpack/src/webpack/webpack.config.ts, packages/flex-plugins-utils-env/src/lib/__tests__/env.test.ts, packages/flex-plugins-utils-env/src/lib/env.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Add support for profile based .env file
* Only support variables that start with FLEX_APP and REACT_APP
=> Env file improvements

.circleci/config.yml
=> Remove nonexistent step from Circle CI validate job 

.travis.yml, packages/flex-plugin-scripts/src/__tests__/index.test.ts, packages/flex-plugin-scripts/src/index.ts
=> try to fix tests for circle-ci

packages/flex-plugin-scripts/src/config/index.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/prints/serverCrashed.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/build.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-webpack/src/devServer/__tests__/ipcServer.test.ts, packages/flex-plugin-webpack/src/devServer/ipcServer.ts, packages/flex-plugin-webpack/src/index.ts
* Log exceptions when a dev-server crashes and exit gracefully
=> log exceptions when dev-servers crash and exit gracefully

packages/flex-plugins-utils-spawn/jest.config.js, packages/flex-plugins-utils-spawn/src/lib/spawn.ts
=> fix spawn on windows

.circleci/config.yml, bin/test-runner.sh, jest.base.js, packages/flex-plugin-e2e-tests/LICENSE, packages/flex-plugin-e2e-tests/README.md, packages/flex-plugin-e2e-tests/jest.config.js, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step001.ts, packages/flex-plugin-e2e-tests/tsconfig.json, packages/flex-plugin-e2e-tests/tsconfig.lint.json
=> setup e2e package

.circleci/config.yml, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step001.ts
=> setup e2e test-job

changelog/v4.md, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Update readme
* Update how we determine isPluginFolder
=> fix how we determine is isPluginFolder

packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step001.ts, packages/flex-plugin-e2e-tests/src/tests/step002.ts, packages/flex-plugin-e2e-tests/src/tests/step003.ts, packages/flex-plugin-e2e-tests/src/tests/step004.ts, packages/flex-plugin-e2e-tests/src/tests/step005.ts, packages/flex-plugin-e2e-tests/src/utils/assertion.ts, packages/flex-plugin-e2e-tests/src/utils/index.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts
More e2e tests:
* `npm i`
* `twilio flex:plugins:test`
* `twilio flex:plugins:build`
=> add more e2e tests

packages/flex-plugin-e2e-tests/README.md, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step006.ts, packages/flex-plugin-e2e-tests/src/tests/step007.ts, packages/flex-plugin-e2e-tests/src/tests/step008.ts, packages/flex-plugin-e2e-tests/src/utils/api.ts, packages/flex-plugin-e2e-tests/src/utils/assertion.ts, packages/flex-plugin-e2e-tests/src/utils/index.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts
=> more e2e tests

.circleci/config.yml, .travis.yml, bin/publish, package.json, packages/flex-plugin-e2e-tests/src/tests/step007.ts
=> add npm-publish workflow

bin/test.js, package.json
* Do not exit with code 1 on windows while we are fixing these tests
=> Make windows not fail

packages/flex-plugin-scripts/src/clients/builds.ts
=> set to node12

packages/flex-plugin-webpack/src/prints/dotEnvIncorrectVariable.ts
Set quiet to false to print warning message
=> Expose env variables

packages/flex-dev-utils/package-lock.json, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/index.ts, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/plugin-flex/package-lock.json, packages/plugin-flex/package.json, packages/plugin-flex/src/commands/flex/plugins/deploy.ts, packages/plugin-flex/src/commands/flex/plugins/start.ts, packages/plugin-flex/src/commands/flex/plugins/upgrade-plugin.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Bump packages
* Remove semver package from plugin-flex and use the flex-dev-utils one
=> bump packages and cleanup deps

packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/logger.ts, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-plugins-utils-logger/src/index.ts, packages/plugin-flex/package.json, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Adds a check for update with custom message (screenshot is for demo purposes - the real example would have proper v4)
=> check for update

packages/create-flex-plugin/package-lock.json, packages/flex-plugin-builder-toolkit/package.json, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-utils-http/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugin/package-lock.json, packages/flex-plugins-utils-logger/package-lock.json, packages/plugin-flex/package-lock.json
=> audit fixes

package-lock.json, package.json, packages/create-flex-plugin/package-lock.json, packages/flex-plugin-builder-toolkit/package-lock.json, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-utils-http/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugins-api-client/package-lock.json, packages/flex-plugins-api-toolkit/package-lock.json, packages/flex-plugins-utils-exception/package-lock.json, packages/flex-plugins-utils-logger/package-lock.json, packages/flex-plugins-utils-spawn/package-lock.json, packages/plugin-flex/package-lock.json
=> audit all packages

.deepsource.toml
request from the security to test out deepsource
=> add deepsource

packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step006.ts, packages/flex-plugin-e2e-tests/src/tests/step009.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts, packages/flex-plugin-e2e-tests/src/utils/plugin-helper.ts
- Test to ensure plugin shows up on Hosted Flex && /plugins contain the plugin
- Hosted Flex base url to test params
=> Added E2E test to verify that released plugin is visible on the Hosted Flex

.circleci/config.yml
- Powershell to WIN PR validator
=> Added powershell to windows PR validator job

packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step002.ts, packages/flex-plugin-e2e-tests/src/tests/step006.ts, packages/flex-plugin-e2e-tests/src/tests/step007.ts, packages/flex-plugin-e2e-tests/src/tests/step008.ts, packages/flex-plugin-e2e-tests/src/tests/step009.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts, packages/flex-plugin-e2e-tests/src/utils/index.ts, packages/flex-plugin-e2e-tests/src/utils/plugins-api.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts
- Support multiple in browser E2E tests
=> Env: browser support

packages/flex-plugin-e2e-tests/src/core/parameters.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts, packages/flex-plugin-e2e-tests/src/utils/console-api.ts, packages/flex-plugin-e2e-tests/src/utils/plugins-api.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts
=> more test cleanup

package-lock.json, package.json, packages/create-flex-plugin/package-lock.json, packages/flex-plugin-builder-toolkit/package-lock.json, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/src/core/runner.ts, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-utils-http/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugins-api-client/package-lock.json, packages/flex-plugins-api-toolkit/package-lock.json, packages/flex-plugins-utils-logger/package-lock.json, packages/flex-plugins-utils-spawn/package-lock.json, packages/plugin-flex/package-lock.json
=> fix the vuln

.circleci/config.yml
- Dropped 'lts' node version from validators
- Added 10/12/14 to WIN pr validator
=> Add node 10/12/14 to win PR validator. Drop LTS node.

packages/flex-plugin-e2e-tests/src/core/index.ts, packages/flex-plugin-e2e-tests/src/core/parameters.ts, packages/flex-plugin-e2e-tests/src/core/runner.ts, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step002.ts, packages/flex-plugin-e2e-tests/src/tests/step005.ts, packages/flex-plugin-e2e-tests/src/tests/step006.ts, packages/flex-plugin-e2e-tests/src/tests/step007.ts
=> test for ts template

.circleci/config.yml
=> try dev build differently

.circleci/config.yml
- When PR validator job passes on changes merged in dev, trigger a npm-publish job with dist;patch
=> Publish to npm on merge to dev

faq.md
=> dummy push

packages/create-flex-plugin/templates/js/src/DemoPlugin.js, packages/flex-plugin-utils-http/package-lock.json, packages/flex-plugin-utils-http/package.json, packages/flex-plugin-utils-http/src/__tests__/http.test.ts, packages/flex-plugin-utils-http/src/http.ts
=> batch calls

packages/flex-plugin-scripts/dev_assets/flex-shim.js
Added shim to proxy when available
=> Added shim to proxy when available

.circleci/config.yml, packages/flex-plugin-e2e-tests/src/core/parameters.ts, packages/flex-plugin-e2e-tests/src/tests/step005.ts
- e2e test for verifying env files
=> Added .env file e2e test

packages/flex-dev-utils/src/__tests__/credentials.test.ts, packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts, packages/flex-plugin-utils-http/src/__tests__/http.test.ts, packages/flex-plugins-utils-env/src/lib/__tests__/env.test.ts, packages/flex-plugins-utils-logger/src/lib/inquirer.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/__tests__/framework.ts, packages/plugin-flex/src/__tests__/sub-commands/create-configuration.test.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/__tests__/utils/parser.test.ts, packages/plugin-flex/src/commands/flex/plugins/diff.ts, packages/plugin-flex/src/commands/flex/plugins/release.ts, packages/plugin-flex/src/commands/flex/plugins/upgrade-plugin.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
- Fixed various linter warnings
=> Linter fixes

packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/plugin-flex/src/commands/flex/plugins/upgrade-plugin.ts
=> fix unbundled react check for default setting

packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/__tests__/semver.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-dev-utils/src/index.ts, packages/flex-dev-utils/src/semver.ts, packages/flex-plugin-scripts/src/prints/index.ts, packages/flex-plugin-scripts/src/prints/localReactIncompatibleWithRemote.ts, packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts, packages/flex-plugin-scripts/src/scripts/pre-script-check.ts, packages/flex-plugin-scripts/src/utils/package.ts
* Check react version match in flex 2.0
=> fix flex 2.0 react check

.circleci/config.yml
=> attempt to fix windows testing

.circleci/config.yml
=> drop node 10 support - add node 16

.circleci/config.yml
=> set npm version

packages/create-flex-plugin/templates/js/src/DemoPlugin.js, packages/create-flex-plugin/templates/js/src/components/CustomTaskList/CustomTaskList.Container.js, packages/create-flex-plugin/templates/js/src/components/CustomTaskList/CustomTaskList.Styles.js, packages/create-flex-plugin/templates/js/src/components/CustomTaskList/CustomTaskList.jsx, packages/create-flex-plugin/templates/js/src/components/__tests__/CustomTaskListComponent.spec.jsx, packages/create-flex-plugin/templates/js/src/index.js, packages/create-flex-plugin/templates/js/src/states/CustomTaskListState.js, packages/create-flex-plugin/templates/js/src/states/index.js, packages/create-flex-plugin/templates/ts/package.json, packages/create-flex-plugin/templates/ts/src/DemoPlugin.tsx, packages/create-flex-plugin/templates/ts/src/components/CustomTaskList/CustomTaskList.Container.ts, packages/create-flex-plugin/templates/ts/src/components/CustomTaskList/CustomTaskList.Styles.ts, packages/create-flex-plugin/templates/ts/src/components/CustomTaskList/CustomTaskList.tsx, packages/create-flex-plugin/templates/ts/src/components/__tests__/CustomTaskListComponent.spec.tsx, packages/create-flex-plugin/templates/ts/src/index.ts, packages/create-flex-plugin/templates/ts/src/states/CustomTaskListState.ts, packages/create-flex-plugin/templates/ts/src/states/index.ts
=> lint template files

packages/flex-dev-utils/src/__tests__/fs.test.ts, packages/flex-dev-utils/src/fs.ts, packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/pre-script-check.test.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/utils/__tests__/parser.test.ts, packages/flex-plugin-scripts/src/utils/package.ts, packages/flex-plugin-scripts/src/utils/parser.ts, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts, packages/flex-plugin-webpack/src/devServer/pluginServer.ts, packages/flex-plugin-webpack/src/index.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/commands/flex/plugins/start.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
Port is now removed from the plugins.json configuration
=> removed 'port' from plugins.json configuration

packages/plugin-flex/package.json
=> Help Text for Multi plugins

packages/flex-plugin-scripts/src/index.ts, packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-scripts/src/utils/__tests__/parser.test.ts, packages/flex-plugin-scripts/src/utils/parser.ts, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts, packages/flex-plugin-webpack/src/devServer/pluginServer.ts, packages/flex-plugin-webpack/src/index.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/commands/flex/plugins/start.ts
support for --name plugin-name@version in start command
=> support for --name plugin-name@version in start command

packages/flex-plugin-scripts/src/scripts/__tests__/start.test.ts, packages/flex-plugin-scripts/src/scripts/start.ts, packages/flex-plugin-webpack/src/devServer/__tests__/pluginServer.test.ts, packages/flex-plugin-webpack/src/devServer/pluginServer.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/commands/flex/plugins/start.ts
=> multi plugin fixes

packages/plugin-flex/package.json, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/commands/flex/plugins/start.ts
Added --port to package.json and updated --name description. Added a default value to the port flag.
=> tweaks before GA

packages/flex-plugin-scripts/src/scripts/pre-script-check.ts
=> word change

packages/flex-plugin-utils-http/package.json, packages/flex-plugin-utils-http/src/__tests__/http.test.ts, packages/flex-plugin-utils-http/src/http.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
Update the CLI to add/remove properties to the user-agent.
=> FLEXY-3749

packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/core/runner.ts, packages/flex-plugin-e2e-tests/src/index.ts, packages/flex-plugin-e2e-tests/src/tests/step004.ts, packages/flex-plugin-e2e-tests/src/utils/browser.ts, packages/flex-plugin-e2e-tests/src/utils/console-api.ts, packages/flex-plugin-e2e-tests/src/utils/pages/view/plugins.ts, packages/flex-plugin-e2e-tests/src/utils/plugin-helper.ts, packages/flex-plugin-e2e-tests/src/utils/spawn.ts, packages/flex-plugin-utils-http/package.json, packages/flex-plugin-utils-http/src/__tests__/http.test.ts, packages/flex-plugin-utils-http/src/http.ts, packages/flex-plugins-api-client/package.json, packages/flex-plugins-api-client/src/clients/__tests__/client.test.ts, packages/flex-plugins-api-client/src/clients/__tests__/plugins.test.ts, packages/flex-plugins-api-client/src/clients/client.ts, packages/flex-plugins-api-client/src/clients/plugins.ts, packages/flex-plugins-api-client/src/clients/serviceHttpClient.ts, packages/flex-plugins-api-toolkit/package.json, packages/flex-plugins-api-toolkit/src/index.ts, packages/flex-plugins-api-toolkit/src/scripts/__tests__/createConfiguration.test.ts, packages/flex-plugins-api-toolkit/src/scripts/__tests__/diff.test.ts, packages/flex-plugins-api-toolkit/src/scripts/createConfiguration.ts, packages/flex-plugins-api-toolkit/src/scripts/diff.ts
=> simplify internal packages dependencies

packages/plugin-flex/src/sub-commands/flex-plugin.ts
* UserAgent should not always require command to run in the directory
=> fix the use of user agent in non-directory uses cases

packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
=> fix the path

packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/commands/flex/plugins/upgrade-plugin.ts, packages/plugin-flex/src/prints/upgradePlugin.ts
Changed conf message for upgrade-plugin command
=> FLEXY-3666 Update information for upgrade plugin command

packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin.test.ts, packages/plugin-flex/src/commands/flex/plugins/archive/plugin.ts
Fix archiving plugin when all environments have already been archived from the archive-versions command
=> Flexy 3855

package-lock.json, packages/plugin-flex/package.json
*Set the required versions of the twilio-cli requirement
=> Set the required versions of the twilio-cli requirement

package-lock.json, packages/plugin-flex/package-lock.json, packages/plugin-flex/package.json, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/__tests__/framework.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
* Upgrading cli-core in plugin-flex for compatibility with Twilio CLI 3
* Fixing tests
=> twilio cli 3 support

package-lock.json, packages/flex-dev-utils/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/plugin-flex/package-lock.json
=> fix security vulns

packages/flex-plugin-scripts/src/scripts/__tests__/deploy.test.ts, packages/flex-plugin-scripts/src/scripts/deploy.ts
=> support 1.n semver versioning

packages/flex-plugin-webpack/package.json
=> pin node-ipc

packages/flex-plugin-scripts/src/clients/builds.ts
=> Migrate to use Node 14

package-lock.json, packages/create-flex-plugin/package-lock.json, packages/flex-dev-utils/package-lock.json, packages/flex-plugin-e2e-tests/README.md, packages/flex-plugin-e2e-tests/package-lock.json, packages/flex-plugin-e2e-tests/src/core/parameters.ts, packages/flex-plugin-e2e-tests/src/tests/step003.ts, packages/flex-plugin-scripts/package-lock.json, packages/flex-plugin-test/package-lock.json, packages/flex-plugin-webpack/package-lock.json, packages/flex-plugin/package-lock.json, packages/plugin-flex/package-lock.json
=> override flex-ui for e2e test

packages/create-flex-plugin/templates/js2/src/DemoPlugin.js, packages/create-flex-plugin/templates/ts2/src/DemoPlugin.tsx, packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/commands/flex/plugins/upgrade-plugin.ts
=> fix some of the regression

packages/create-flex-plugin/templates/js2/package.json, packages/create-flex-plugin/templates/js2/src/DemoPlugin.js, packages/create-flex-plugin/templates/js2/src/index.js, packages/create-flex-plugin/templates/ts2/package.json, packages/create-flex-plugin/templates/ts2/src/DemoPlugin.tsx, packages/create-flex-plugin/templates/ts2/src/index.ts
* adding correct scoped package to v2 templates
* adding manager back to v2 template code
=> added scoped package to v2 templates, added manager to init

packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
Fixing the builder version for v6
=> Fixing the builder version for v6

changelog/v6.md
Added changelog for version 6.x
=> Added changelog for version 6.x

packages/plugin-flex/src/sub-commands/flex-plugin.ts
Fixed @oclif/core 1.19.0 compatibility issue
=> Fixed @oclif/core 1.19.0 compatibility issue

changelog/v6.md
Update for changelog for 6.0.3
=> Update changelog for 6.0.3

.circleci/config.yml, packages/flex-plugin-e2e-tests/src/utils/pages/view/base.ts, packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> FLEXY-4389 Fix e2e tests

changelog/v6.md, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin-version.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/archive/plugin.test.ts, packages/plugin-flex/src/commands/flex/plugins/archive/plugin-version.ts, packages/plugin-flex/src/commands/flex/plugins/archive/plugin.ts
=> FLEXY-4506

packages/plugin-flex/src/commands/flex/plugins/create.ts
=> FLEXY-4848: dummy

.github/workflows/e2e_nightly.yaml
Check scheduled runner with github action
=> FLEXY-4848: check scheduled runs

changelog/v6.md, packages/flex-plugin-webpack/src/webpack/webpack.config.ts
Added a fix for global is undefined error.
=> Flexy 3002 patch 6.2.2

changelog/v6.md, packages/flex-plugin-scripts/src/clients/builds.ts
Bumping serverless node version to 18
=> FLEXY-4772 Bumping serverless node version to 18

.github/workflows/e2e_nightly.yaml
Remove commit username from slack alerts
=> Remove commit name from notification

.github/workflows/manual_public_release.yaml, .github/workflows/~reusable_publish.yaml
Fixing public release pipeline
=> add github user

.github/workflows/~reusable_publish.yaml
=> Fix publish pipeline

.github/workflows/~reusable_publish.yaml
=> add ssh key

.github/workflows/~reusable_publish.yaml
=> change action url

bin/publish
=> remove test on publish

.github/workflows/~reusable_publish.yaml
=> change name

.github/workflows/~reusable_publish.yaml
=> added ssh key for publish

.circleci/config.yml, .circleci/configs/e2e_test.yml, .circleci/configs/npm_publish.yml, .circleci/configs/pr_validator.yml
=> Added circleci config

.github/workflows/~reusable_publish.yaml, bin/publish
=> check PR create

.github/workflows/manual_public_release.yaml, .github/workflows/~reusable_publish.yaml
=> let use APPI_ID

bin/publish
=> circleci publish

.github/workflows/manual_public_release.yaml
=> add secret

.github/workflows/~reusable_public_publish.yaml, bin/publish
=> use version for commit

.github/workflows/~reusable_public_publish.yaml
=> add git user

.github/workflows/~reusable_public_publish.yaml
=> change user

.github/workflows/~reusable_public_publish.yaml, bin/publish
=> Commit with PR

.github/workflows/~reusable_public_publish.yaml
=> add branch env

.github/workflows/check_public_release.yaml, .github/workflows/e2e_skip.yaml, .github/workflows/manual_public_release.yaml, .github/workflows/pr_workflow.yaml, .github/workflows/pr_workflow_skip.yaml, .github/workflows/~reusable_public_publish.yaml
=> Commit with lib

.github/workflows/pr_workflow_skip.yaml, .github/workflows/~reusable_public_publish.yaml
=> fix branch name and use auto

.github/workflows/manual_public_release.yaml, .github/workflows/pr_workflow.yaml, .github/workflows/pr_workflow_skip.yaml, .github/workflows/tag.yaml, .github/workflows/~reusable_public_publish.yaml
Stop PR flow on version update
=> stop pr flow on version

.github/workflows/manual_public_release.yaml, bin/publish
=> remove dependency

.github/workflows/manual_public_release.yaml, .github/workflows/~reusable_public_publish.yaml
Send Notification while publish
=> add notification

changelog/v6.md
=> Cleaned up CHANGELOG

packages/flex-plugins-api-client/src/clients/pluginVersions.ts, packages/plugin-flex/src/commands/flex/plugins/deploy.ts
Pass the CLI version parameter when creating versions.
=> Modify version parameter

.github/workflows/~reusable_public_publish.yaml, bin/publish
=> Enable npm push & Auto-merge

package-lock.json, packages/create-flex-plugin/src/index.ts, packages/flex-dev-utils/package.json, packages/flex-dev-utils/src/updateNotifier.ts, packages/flex-plugin-scripts/src/index.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/start.test.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/upgrade-plugin.test.ts, packages/plugin-flex/src/__tests__/sub-commands/flex-plugin.test.ts, packages/plugin-flex/src/commands/flex/plugins/create.ts, packages/plugin-flex/src/sub-commands/flex-plugin.ts
Fixed update notifier and added deprecation notice.
=> Fixed update notifier and added deprecation notice

packages/flex-plugin-scripts/src/scripts/__tests__/validate.test.ts, packages/flex-plugin-scripts/src/scripts/validate.ts, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts, packages/plugin-flex/src/commands/flex/plugins/deploy.ts
Integrated with the new twilio error response format
=> Integrated with the new twilio error response format

changelog/v7.md, packages/plugin-flex/src/__tests__/commands/flex/plugins/deploy.test.ts
Update changelog for v7.0.1 and update unit tests
=> FLEXY-5303 update changelog for v7.0.1

.github/workflows/e2e.yaml, .github/workflows/~reusable_e2e_2.yaml
=> schedule test

.github/workflows/e2e.yaml
=> remove time check

.github/workflows/e2e.yaml, .github/workflows/~reusable_e2e_2.yaml
=> multi schedule testing

.github/workflows/e2e.yaml
=> make separate

.github/workflows/e2e.yaml, .github/workflows/~reusable_e2e_2.yaml
=> pass slack webhook url

.github/workflows/e2e.yaml, .github/workflows/~reusable_e2e_2.yaml
Add retry for timeout jobs and change schedule timing
=> Add retry for timeout jobs and change schedule timing

.github/workflows/manual_alpha_release_v6.yaml, .github/workflows/manual_public_release_v6.yaml
=> FLEXY-5323 v6 test for cheerio fix

.github/workflows/manual_alpha_release_v6.yaml, .github/workflows/manual_public_release_v6.yaml, .github/workflows/~reusable_public_publish.yaml
=> FLEXY-5323 minor change

.github/workflows/~reusable_public_publish.yaml
=> FLEXY-5323 fixed formatting issue in yml

.github/workflows/~reusable_e2e_by_OS.yaml
Fix slack notification for nightly E2E
=> Update slack notification

changelog/v7.md, packages/flex-dev-utils/src/fs.ts
=> FLEXY-5434 fix for plugin release from any directory

.github/workflows/~reusable_e2e_all_OS.yaml
Fixing issue with manual release workflow
=> add slack title to e2e flow

.github/workflows/e2e_scheduled_jailbreak.yaml
=> Adding a new job for Jailbreak

packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> Including credentials for /submitloginpassword

.github/workflows/e2e_scheduled.yaml, .github/workflows/e2e_scheduled_jailbreak.yaml, packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> Updating cron job time

packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> Flexy 00000 -  Login failure fix

packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> FLEXY- minor fix for e2e login

package-lock.json, packages/flex-plugin-e2e-tests/package.json, packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> Fix _.this Error with E2E

.github/workflows/e2e_scheduled.yaml, .github/workflows/e2e_scheduled_jailbreak.yaml, .github/workflows/~reusable_e2e_all_OS.yaml, .github/workflows/~reusable_e2e_by_OS.yaml, packages/flex-plugin-e2e-tests/src/utils/pages/view/twilio-console.ts
=> Run e2e node 18

.github/workflows/e2e_scheduled.yaml
=> Fix typo in scheduled job

packages/flex-plugin-e2e-tests/src/utils/pages/view/base.ts
Adding catch error and log for e2e
=> Adding catch error and log for e2e
